### ISSUE TITLE
Change repo name & GitHub packages

### ISSUE THREAD

**Issue by acmlira** [TotalCross/totalcross-maven-plugin#14]
## Repo name

I was thinking about our repositories and reach a conclusion: almost of all names are something like `totalcross-something` but we are already in organization called _TotalCross_ and than in GitHub syntax these repositories are something like:

`TotalCross/totalcross-something`

So, I think it may be more semantic to exclude this `totalcross` from this and other repositories. My proposal is: give a cool name to project. Like `KnowCode` it isn't called `java-xml-conversor`. `maven-plugin` is kinda generic you know?

## GitHub packages

Today we spend bandwidth from some proprietary server to provide the maven plugin. My suggestion is to pass this responsibility on to _GitHub_ with _GitHub packages_, I saw little about it and would still like to know if it is possible or not. Here are some references:

1. https://dev.to/iamthecarisma/hosting-a-maven-repository-on-github-site-maven-plugin-9ch
2. https://stackoverflow.com/questions/61136940/how-to-upload-maven-plugin-to-github-packages

**Comment by ItaloYeltsin** [comment]
Well, in regard to the name, I don't agree. You can see many maven plugin repositories and it's kinda a pattern naming maven plugin projects as ${name}-maven-plugin, [see](https://github.com/search?q=maven-plugin). Maybe, for other project what you are saying fits perfectly, but this is not the case. 

In relation to maven artifact repository, I think we do have to get rid of our own repository. However, using github packages requires a little change in our user projects `pom.xml` which is pointing the artifact repository to it's link on github.

```xml
<repository>
    <id>ARTIFACT-ID</id>
    <url>https://raw.github.com/REPOSITORYOWNER/REPOSITORY-NAME/mvn-repo/</url>
</repository>
```
So, the best option to avoid changes in the user's pom file is to deploy to the maven central repository. By doing that, our users don't have to adapt their projects to get a new `totalcross-maven-plugin` version. See the link bellow to learn how to upload to the central maven repo.

https://dzone.com/articles/publish-your-artifacts-to-maven-central
